### ISSUE TITLE
[Bug : Concatenate Tours] 

### ISSUE THREAD

**Issue by PaloH17** [mytourbook/mytourbook#1330]
### What happened ?

I concatenated two tours with the option "Keep original start time for each tour". The second one started in a different place (B) than the first one finished (A).  Parameters of the resulting tour are fine except for Elevation loss. This value clearly includes the difference in the elevation of places A and B. 

This is, in my opinion, an incorrect behaviour. If other parameters as distance, average speed, etc. are calculated only from the values recorded in the original tours, the same should be used for calculating Elevation gain and loss. Or there should be, at least, an option to set this behaviour.

Consider an example: I will go on two hikes on the same day and in two nearby areas.  So I wish to concatenate the hikes to a single tour.  However, I will drive between the hikes and there is no reason to count the elevation gained in the car.

### Version

24.1.0

### System

Windows

**Comment by wolfgang-ch** [comment]
> Parameters of the resulting tour are fine except for Elevation loss.

The elevation gain is also wrong

**Comment by wolfgang-ch** [comment]
This is fixed in the next version

There can be small differences between the joined elevation values and when the tour elevation values are summarized

![image](https://github.com/mytourbook/mytourbook/assets/1283445/cf4109fc-33ef-46ae-b14b-3b9c567e1fc2)

**Comment by PaloH17** [comment]
I just downloaded 24.5.0 and tested the tour concatenation. Immediately after the concatenation, elevation gain and loss values seem O.K. but when the concatenated tour is edited (changed title) and saved, the wrong values appear again.

**Comment by FJBDev** [comment]
@PaloH17 
Did you make sure to uncheck that box ? Maybe when you saved it has recomputed the elevation gain/loss values

![image](https://github.com/mytourbook/mytourbook/assets/25235665/7bdf8451-fa1c-4774-8480-05ed89c6533d)

**Comment by PaloH17** [comment]
Yes, the Recompute ... option was checked. After unchecking it and re-joining the source tours, gain/loss values are as expected. 
However, I am still missing something. If the source tours are saved separately, the option has no influence. Why does the tour concatenated with the option checked includes the elevation difference of source tours? Recomputing elevation values (using either device or SRTM values) should not have this effect.

**Comment by wolfgang-ch** [comment]
We could keep the fields `joinedElevationDiffUp` and `joinedElevationDiffDown` in separated fields in a saved tour and subtract it always after recomputing the elevation up/down value, but these values can be wrong when time slices in a concatenated tour are deleted and then it can get really complicated to cover all possible modifications.


![grafik](https://github.com/mytourbook/mytourbook/assets/1283445/2793cd62-6ac6-4fe4-b0e6-2d20286e1200)

**Comment by PaloH17** [comment]
I've never used time slices in MTB.  Now, I've looked at them and I have to admit that the deletion options are really quite complex.

So, I have a somewhat modified suggestion: User could manually insert a pair of start and end marks (you can think them as dummy time slices) that indicates the tour part to be used for evaluation. More pairs could be added  (immediately or after skipping some time slices) with the same meaning. These and only these parts would then enter in the calculations of tour parameters. Exact algorithms how to treat particular types of tour values you have certainly already developed - it should be the same what is used when tours are concatenated.  The pair of marks covering a whole tour should be inserted by default. Identification of the above marks with `<trkseg>` tags on import could be an option. Similary, the insertion of the marks during the concatenation that surround the original tours.

The marks should be always saved with the tour. It would be a user responsibility whether the marks are at correct positions, the software would just check that the start and end marks are paired and possibly also that there is no overlap between particular pairs. The check should be repeated especially if time slices are modified.  If there is some discrepancy in mark positions the user should be warned and all marks ignored (but preserved in the tour).

Maybe technical solution could be different, it's just a thought that came to me quickly. Main idea is 1. there should be a robust procedure that allows repeatedly for calculating the tour parameters depending only on well-defined parts of a tour, not on some auxiliary parameters and 2. the user is responsible for defining these parts.

**Comment by wolfgang-ch** [comment]
With your suggestion in my mind I have this idea:

Create subtour markers which can be set to any time slice and are set automatically when tours are concatenated. The difference values between a subtour marker time slice and the previous time slice are ignored when e.g. elevation up/down values are computed.

To implement this feature, it needs some work to implement also the UI elements to create/delete/display the subtour markers in the tour editor, chart and map

I'm using the wording "sub" because the word "tour segments" are already used since 15+ years for another purpose
