### ISSUE TITLE
[FeatureFromSF] Export to FIT/ Garmin Connect

### ISSUE THREAD

**Issue by wolfgang-ch** [mytourbook/mytourbook#845]
Please make a possibility to export to FIT file for Import in Garmin Connect or better, sync with Garmin Connect, Strava or whatever.

Reported by: snowheaven

Original Ticket: [mytourbook/feature-requests/193](https://sourceforge.net/p/mytourbook/feature-requests/193)

**Comment by mff73** [comment]
Hello,
I am not sure how to vote or to see vote numbers for "feature requests", and particularly this one :)
is fit export format could be considered from MTB ?
thanks.

**Comment by FJBDev** [comment]
> I am not sure how to vote or to see vote numbers for "feature requests"

This is something I have wondered for a long time now and I am not sure this is possible. There is [this ](https://github.com/isaacs/github/issues/1533)request to add in Github but it doesn't seem that it was ever taken into account.

However, I found [this plugin](https://github.com/apex/gh-polls) that seems to support polling for GitHub issues

**Comment by mff73** [comment]
Thanks Fred, and what about fit export 😁 ?
As MTB is able to concatenate activities, fix altitude, calculate distance, edit/delete part of it, etc, it would be so nice to be able to export the resulting activity in an official fit file (following sdk rules).

**Comment by FJBDev** [comment]
It is a possibility to add the FIT export but not sure when that would be implemented.
In the meantime, are you using tools like [TCX Converter ](https://tcx-converter.software.informer.com/2.0/)to convert files from MT that are exported in TCX ?

**Comment by mff73** [comment]
i try to download this tcx converter but i can't manage to download anything :(
did you have it downloaded and could share it with any cloud link, please ? 
it could be a perfect idea if it is working.
thanks Fred.

**Comment by FJBDev** [comment]
Hmmm, Im experiencing the same issue, it seems that their download link is broken at the moment.

In this, case I would recommend you try to use [GoldenCheetah ](https://www.goldencheetah.org)as it allows to export in FIT (I tried today and was able to download it and export in FIT 😄 )

**Comment by mff73** [comment]
Tried also GoldenCheethah (before you 😇), it exports FIT, ...... but : 
i need to investigate why, but GC fit file is not well digested by Suunto (while trying to import it through Runalyze which is connected to SuuntoAPI for fit import).
To be fully clear about my use case. MTB is my offline database for ALL my activities : it replaces sporttracks like many others. But i also want to have my activities in Suunto cloud and as well as possible syncronized with MTB. Example if unfortunately i need to create 2 activities in Suunto for the same tour, i can concatenate them in MTB, and i would like to reimport the concatenation in Suunto.
GoldenCheetha is promising, but strange that their fit file is not accepted by Suunto 🤔

**Comment by FJBDev** [comment]
>To be fully clear about my use case. MTB is my offline database for ALL my activities : it replaces sporttracks like many others. 

Same here 😃 !

> But i also want to have my activities in Suunto cloud and as well as possible syncronized with MTB. Example if unfortunately i need to create 2 activities in Suunto for the same tour, i can concatenate them in MTB, and i would like to reimport the concatenation in Suunto. GoldenCheetha is promising, but strange that their fit file is not accepted by Suunto 🤔

Weird, I would actually report that to GC as it is not normal that their FIT file is not accepted by Suunto.

> [EDIT] in the new fit SDK, there is a ActivityRepairTool which seems to fix the GoldenCheethah files (at least for SuuntoImport). I think my process could become : manipulate activities in MTB, Transfer to GC in TCX, Export in FIT, and repair it before import to Suunto again. Some missing data in GC fit files though :( Total Ascent/Descent, and surely Laps/Pauses (but i need to check).

That could be a possible workflow for now but it's very "manual intensive". I think in the long run, it might be best to do this:
- Add the ability to export a tour from MT in FIT format.
- Add the ability to upload a tour from MT directly to Suunto App thanks to their [Suunto Upload API endpoint](https://apizone.suunto.com/docs/services/suunto-upload-api/operations/init-upload) and then it would be only 2 clicks 😄

**Comment by mff73** [comment]
> That could be a possible workflow for now but it's very "manual intensive". I think in the long run, it might be best to do this:
> 
> * Add the ability to export a tour from MT in FIT format.
> * Add the ability to upload a tour from MT directly to Suunto App thanks to their [Suunto Upload API endpoint](https://apizone.suunto.com/docs/services/suunto-upload-api/operations/init-upload) and then it would be only 2 clicks 😄

🙏🙏😇😇❤

**Comment by mff73** [comment]
Hi Fred, I see you assigned this to you : soooooo great 😊.
If you need any help to test, don't hesitate.
Thanks.

**Comment by FJBDev** [comment]
> Hi Fred, I see you assigned this to you : soooooo great 😊. 

Yes, I started working on it but I first wanted to do the Tags feature, then I have another feature I want to finish and next I will finish implementing this one.

> If you need any help to test, don't hesitate. Thanks.

Sure, I will let you know when a test version is ready. Your testing will be very useful to ensure that it's ready to be released

**Comment by FJBDev** [comment]
@mff73  I plan on having a test version ready in the next few days that will contain the FIT export as well as the Suunto App Workout Upload. Which OS do you use ? (so that I generate the executable for that OS)

**Comment by mff73** [comment]
@FJBDev, I am using windows.
It is a wonderful news. I am on vacation and few activities would require some modifications 👍.
Thanks in advance for all your work.

**Comment by FJBDev** [comment]
@mff73 
I have created a development build that you can download [here](https://www.dropbox.com/s/jdlzplekn5cxp2a/mytourbook-23.NEXT-FITEXPORT-win-setup.exe?dl=0) and install locally so you can test the FIT export and Suunto Workout Upload

:warning: **VERY IMPORTANT** :warning:: You MUST NOT use your current MyTourbook database because any changes in this test (development) version, e.g. tour database version, can cause lots of troubles when you install again the current official release version.
If you REALLY want to use your current MyTourbook database, PLEASE BACKUP your database first as this build is **NOT** an official release. That way, once you uninstall it and install the official release again, you can restore your data unaltered.

See the [official documentation](http://mytourbook.sourceforge.net/mytourbook/index.php/documentation/backup) here on how to backup the database

Let me know and thanks for your testing

**Comment by mff73** [comment]
It is downloading, thanks a lot, i will test with backuped db 😊😊

**Comment by mff73** [comment]
@FJBDev 
little busy these days, but test built is installed and just a quick test done : it is working :)
I didn't yet dig into deeper checks and test though.
First very quick comment about the activity type : we may have to think about how to map MTB activity type with Suunto (fit) ones. I exported successfully a "Trail" activity from MTB, which results in a "other" activity in Suunto.

**Comment by FJBDev** [comment]
> @FJBDev little busy these days, but test built is installed and just a quick test done : it is working :) 

👍 

>First very quick comment about the activity type : we may have to think about how to map MTB activity type with Suunto (fit) ones. I exported successfully a "Trail" activity from MTB, which results in a "other" activity in Suunto.

Indeed, this one is not easy because mainly the fact that users will use different languages whereas the FIT sport definition is in English.
This is what [I have for now ](https://github.com/FJBDev/mytourbook/blob/fb-exportfit/bundles/net.tourbook.export/src/net/tourbook/export/fit/FitSportMapper.java)that will use the tour type in MT and tries to map it to a FIT sport type.
I am open to suggestions though

The GARMIN sport types as of the Garmin FIT SDK 21.105:

```

ALL
ALPINE_SKIING
AMERICAN_FOOTBALL
BASKETBALL
BOATING
BOXING
CROSS_COUNTRY_SKIING
CYCLING
DIVING
DRIVING
E_BIKING
FISHING
FITNESS_EQUIPMENT
FLOOR_CLIMBING
FLYING
GENERIC
GOLF
HANG_GLIDING
HIIT
HIKING
HORSEBACK_RIDING
HUNTING
ICE_SKATING
INLINE_SKATING
INVALID
JUMPMASTER
KAYAKING
KITESURFING
MOTORCYCLING
MOUNTAINEERING
MULTISPORT
PADDLING
RACKET
RAFTING
ROCK_CLIMBING
ROWING
RUNNING
SAILING
SKY_DIVING
SNOWBOARDING
SNOWMOBILING
SNOWSHOEING
SOCCER
STAND_UP_PADDLEBOARDING
SURFING
SWIMMING
TACTICAL
TENNIS
TRAINING
TRANSITION
WAKEBOARDING
WAKESURFING
WALKING
WATER_SKIING
WATER_TUBING
WINDSURFING
```

**Comment by mff73** [comment]
Hi @FJBDev ,
Sorry for late answer and test.
I found two issues for one current real life use case.

First issue :
Concatenate two tours in MTB to create a unique one (for example when you stopped an activity and restart a new one some time later).
Like this : 

![image](https://user-images.githubusercontent.com/50132146/235287876-dd7c40ff-d49a-4098-b8e1-391abd6eab25.png)

i used these options in MTB : 
![image](https://user-images.githubusercontent.com/50132146/235287911-a4d029dd-38bc-4cc5-b69d-2a9ca4da7653.png)

and got this error
![image](https://user-images.githubusercontent.com/50132146/235287984-f4369096-72b7-47f5-a34f-1f83ef5c5b9b.png)

if i removed the option "inclure les marqueurs.....", it worked and my tour is sent to suunto.

Second issue : 
i know that Suunto has strange way to handle pauses for activity imports, thus the second issue might not be due to MTB, but maybe yes.
The data graphs in SuuntoApp are not displayed after the pause just first part of the concatenated activity is displayed (in my example : 20min17s

if i view the resulting fit file exported from MTB, i see that timer events looks a bit strange to me
There is a stop_all at the same timestamp of the initial start
And there is a data column for events (strange ?)
here in fitfileviewer
![image](https://user-images.githubusercontent.com/50132146/235288507-291d80bb-ddd1-4bf2-ad00-6f478ed10462.png)
here in csv fit file
![image](https://user-images.githubusercontent.com/50132146/235289361-56d94c70-4bca-4387-b57e-c5794f002f70.png)


I manage to fix the issue changing manually the fit file, like this : removing the event stop all at the start time (main issue) and removing the "data" column (not sure which impact it has finally (not checked sorry :) )
![image](https://user-images.githubusercontent.com/50132146/235289440-6074ec6e-708a-4751-af80-c65396400a13.png)

hope it is clear, i can send you my files by email if you can't reproduce easily this with some of your activities ;) (just ask me).

but all in all, it is very promising (and potentially, some other suunto users may love MTB (at least for this ;) when it will be perfect).

**Comment by mff73** [comment]
oups, other issue (sorry)
speed is exported in km/h, while unit is m/s, i am really fast now 🤣
![image](https://user-images.githubusercontent.com/50132146/235289865-28480dc0-0dcf-4627-9fa3-5637835d8f56.png)

**Comment by FJBDev** [comment]
> Hi @FJBDev , Sorry for late answer and test. I found two issues for one current real life use case.
> 
> First issue : Concatenate two tours in MTB to create a unique one (for example when you stopped an activity and restart a new one some time later). Like this :
> 
> ![image](https://user-images.githubusercontent.com/50132146/235287876-dd7c40ff-d49a-4098-b8e1-391abd6eab25.png)
> 
> i used these options in MTB : ![image](https://user-images.githubusercontent.com/50132146/235287911-a4d029dd-38bc-4cc5-b69d-2a9ca4da7653.png)
> 
> and got this error ![image](https://user-images.githubusercontent.com/50132146/235287984-f4369096-72b7-47f5-a34f-1f83ef5c5b9b.png)
> 
> if i removed the option "inclure les marqueurs.....", it worked and my tour is sent to suunto.
> 
> Second issue : i know that Suunto has strange way to handle pauses for activity imports, thus the second issue might not be due to MTB, but maybe yes. The data graphs in SuuntoApp are not displayed after the pause just first part of the concatenated activity is displayed (in my example : 20min17s
> 
> if i view the resulting fit file exported from MTB, i see that timer events looks a bit strange to me There is a stop_all at the same timestamp of the initial start And there is a data column for events (strange ?) here in fitfileviewer ![image](https://user-images.githubusercontent.com/50132146/235288507-291d80bb-ddd1-4bf2-ad00-6f478ed10462.png) here in csv fit file ![image](https://user-images.githubusercontent.com/50132146/235289361-56d94c70-4bca-4387-b57e-c5794f002f70.png)
> 
> I manage to fix the issue changing manually the fit file, like this : removing the event stop all at the start time (main issue) and removing the "data" column (not sure which impact it has finally (not checked sorry :) ) ![image](https://user-images.githubusercontent.com/50132146/235289440-6074ec6e-708a-4751-af80-c65396400a13.png)
> 
> hope it is clear, i can send you my files by email if you can't reproduce easily this with some of your activities ;) (just ask me).
> 
> but all in all, it is very promising (and potentially, some other suunto users may love MTB (at least for this ;) when it will be perfect).

Thanks for your further testing.
Actually, in the meantime, I fixed several issues I found myself and that Wolfgang found and I believe it should have fixed the issues related to the pauses and markers you found.

I will give you an updated test version so you can verify that those are fixed

**Comment by FJBDev** [comment]
> oups, other issue (sorry) speed is exported in km/h, while unit is m/s, i am really fast now 🤣 ![image](https://user-images.githubusercontent.com/50132146/235289865-28480dc0-0dcf-4627-9fa3-5637835d8f56.png)

Thanks, I will fix that !!

**Comment by mff73** [comment]
Thanks Fred !
I really like this new feature : sounds like it will become a real killer to get MTB perfect offline app, but also to keep online plateform (at least Suunto for me) updated with "fixed" activities 🤞🙏👍
I will test quicker your new version 😊

**Comment by FJBDev** [comment]
@mff73 

[Here](https://www.dropbox.com/s/0ru56afcic8nhxr/mytourbook-23.3.2-win-setup-FITEXPORT-PART2.exe?dl=0) is an updated version that should contain fixed for pauses/markers and speed that you mentioned above.

Thanks again for your testing!

**Comment by mff73** [comment]
@FJBDev 
Thanks for your work on this.
it is better (almost perfect) :  but, still an error with a stop_all event at the same timestamp than the start of activity :(

![image](https://user-images.githubusercontent.com/50132146/235486167-0f1d57ba-e503-4c97-9168-dd7b1396f367.png)

it doesn't prevent the file to be uploaded into Suunto, but activity graphs and replay are not displayed after this stop_all.

this activity in MTB, is  concatenated from two other Suunto activities.
Do you need me to send you original files ?

Extra question : did you manage to export sport and sub_sport as well (it seems) ?

Thanks again.

**Comment by FJBDev** [comment]
> @FJBDev Thanks for your work on this. it is better (almost perfect) : but, still an error with a stop_all event at the same timestamp than the start of activity :(

Thanks for your quick testing and feedback.
[Here](https://www.dropbox.com/s/c6o89vymytzhz90/mytourbook-23.3.2-win-setup-FITEXPORT-PART3.exe?dl=0) is an updated version that should address this issue.

> this activity in MTB, is concatenated from two other Suunto activities. Do you need me to send you original files ?

If the latest test version still has the same issue, yes, please send me the files so I can analyze it better locally.

> Extra question : did you manage to export sport and sub_sport as well (it seems) ?
> 
Yes, see my answer [above](https://github.com/mytourbook/mytourbook/issues/845#issuecomment-1515472101)

>Thanks again.

You're welcome, thanks for your thorough testing

**Comment by mff73** [comment]
YOU DID IT !!! 😊👍

For this use case of mine, it works perfectly and in two clicks or so, i am fixing my activities in Suunto.

Will see with normal daily usages and report anything which could be improved or fixed if really needed 🥳

PS: would you prefer present this feature in SA forum (youself or me) or keep it undiscovered for now ? i am pretty sure MTB could become "fit fixer", with the risk of lots of "tickets" if not working properly each time for ALL use cases.

**Comment by FJBDev** [comment]
> YOU DID IT !!! 😊👍

Glad to hear that I fixed it, I guess it's ready to be released once I merge those fixes to the `main` branch
> 
> For this use case of mine, it works perfectly and in two clicks or so, i am fixing my activities in Suunto.
> 

Indeed, only 2 clicks. The less clicks the better.


> Will see with normal daily usages and report anything which could be improved or fixed if really needed 🥳

Indeed and feel free to report any issues. I also plan to change the Strava upload to use FIT format instead of TCX (format used as of today and since the beginning)

> PS: would you prefer present this feature in SA forum (youself or me) or keep it undiscovered for now ? i am pretty sure MTB could become "fit fixer", with the risk of lots of "tickets" if not working properly each time for ALL use cases.

You can present this feature to the SA forum if you feel like people could benefit from it.

Thank you again for your testing @mff73 !
